site_name: devansh's notes
plugins:
  - search
  - git-revision-date
theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - revision.date
markdown_extensions:
  - def_list
nav:
  - home: 'index.md'
  - devops:
    - Index: 'devops/index.md'
    - jenkins: 'devops/jenkins.md'
